dataDir: /var/local/zerossl # Data directory for containing the status and temporary files
logFile: /var/local/zerossl/log.txt # Log file
cleanUnfinished: true # Clean zerossl certificates that are not finished issuing.
certConfigs:
  # Use confId to identify the certificate configuration 将 commonName 改为服务器 ip 或域名
  - commonName: 4.3.2.1
    # mandatory
    confId: xx1
    # your zerossl api key 下面填上 api key
    apiKey: xxx-xxx
    ######## CSR INFO ########
    country: US
    province: CA
    city: San Francisco
    locality: San Francisco
    organization: Earth
    organizationUnit: Development
    ######## CSR INFO ########
    # certificate validity in days
    days: 90
    # key type, ecdsa or rsa
    keyType: ecdsa
    # rsa key bits
    keyBits: 2048
    # ecdsa curve, P-256 or P-384
    keyCurve: P-256
    # signature algorithm, ECDSA-SHA256 or SHA256-RSA or ECDSA-SHA384 or SHA384-RSA
    sigAlg: ECDSA-SHA256
    # fixed
    strictDomains: 1
    # fixed
    verifyMethod: HTTP_CSR_HASH
    # 后面的几个目录都可以自行修改
    # verify hook executable, will be called before verifying domains 需要先下载/修改好 hook 脚本，然后配置对应目录
    verifyHook: /var/local/zerossl/verify-hook.sh
    # post hook executable, will be called after certificates arrival 需要先下载/修改好 hook 脚本，然后配置对应目录
    postHook: /var/local/zerossl/post-hook.sh
    # certificate store path 证书存放位置
    certFile: /var/local/zerossl/cert0.pem
    # key store path 证书key存放位置
    keyFile: /var/local/zerossl/key0.pem

# 不弄第二个域名所以后面的删了，有需求去上游仓库拿来改
